chore: replace golangci-lint by staticcheck

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -166,12 +166,24 @@ jobs:
       - prepare
       - run: make deps
       - run:
-          command: make -j3 support/tools/bin/golangci-lint
+          name: Install staticcheck
+          command: go install honnef.co/go/tools/cmd/staticcheck@434f5f3816b358fe468fa83dcba62d794e7fe04b # 2021.1 (v0.2.0)
       - run:
-          name: Lint
+          name: gofmt
           command: |
-            support/tools/bin/golangci-lint run -v \
-              --timeout 5m --concurrency << parameters.concurrency >> ./...
+            out=$(gofmt -s -l .)
+            if [[ -n "$out" ]]; then
+              echo $out | awk '{print "::error file=" $0 ",line=0,col=0::File is not gofmt-ed."}'
+              exit 1
+            fi
+      - run:
+          name: go vet
+          command: go vet ./...
+      - run:
+          name: staticcheck
+          command: |
+            set -o pipefail
+            staticcheck ./... | sed -e 's@\(.*\)\.go@./\1.go@g'
   lint-all:
     <<: *lint
   test-docker:
